[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "esmfold2"
platforms = [{ platform = "linux-64", cuda = "13" }]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
polars = ">=1.44.2,<2"
flash-attn = ">=2.8.3,<3"
xformers = ">=0.0.34,<0.0.35"
pytorch = "2.11.*"
cuda-cudart-dev = ">=13.4.92,<14"

[pypi-dependencies]
esm = ">=3.4.1.post1, <4"
